### ISSUE TITLE
一直提示文件不存在

### ISSUE THREAD

**Issue by realjackwang** [Glory133172007/github-action-example#1]
为什么我运行一直显示文件不存在呢？

根据readme配置好了环境变量，但是运行的时候无论是用file，还是dir都是文件不存在

这是我的仓库地址，麻烦帮我检查一下yml的代码

https://github.com/realjackwang/sfc_automations

yml：
```
name: Deploy-Functiongraph

on:
  push:
    branches: 
    - 'master'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: deploy single function file to huaweicloud functiongraph
      uses: huaweicloud/deploy-functiongraph-action@v1.0.4

      with:
        ak: ${{ secrets.ACCESSKEY }}
        sk: ${{ secrets.SECRETACCESSKEY }}
        endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com
        project_id: ${{ secrets.PROJECT_ID }}
        function_urn: urn:fss:cn-north-4:${{ secrets.PROJECT_ID }}:function:default:${{ secrets.FUNCTIONNAME}}:latest
        function_codetype: file
        function_file: ./simple/function/index.py
```

日志：
```
Run huaweicloud/deploy-functiongraph-action@v1.0.[4](https://github.com/realjackwang/sfc_automations/actions/runs/4230057494/jobs/7346997644#step:3:4)
  with:
    ak: ***
    sk: ***
    endpoint: https://functiongraph.cn-north-4.myhuaweicloud.com/
    project_id: ***
    function_urn: urn:fss:cn-north-4:***:function:default:***:latest
    function_codetype: file
    function_file: ./simple/function/index.py
---------- check base[6](https://github.com/realjackwang/sfc_automations/actions/runs/4230057494/jobs/7346997644#step:3:6)4 on system
base64 already installed and set to the path
[object Promise]
---------- check input parameters
get currentRegion : cn-north-4
get currentRegion : cn-north-4
---------- check file content
[object Promise]
file or directory not exist
Error: check file content error
```
